# main menu
[[main]]
name = "Meal Plans"
url = "all-plans/"
weight = 1

[[main]]
name = "Dine in Locations"
url = "locations/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
name = "Customer Story"
url = "customers-story/"
weight = 4

[[main]]
identifier = "company"
name = "Company"
url = "#"
weight = 5

[[main]]
identifier = "our-story"
name = "Our Story"
url = "about-us/"
parent = "company"
weight = 1

[[main]]
identifier = "faqs"
name = "FAQs"
url = "faq/"
parent = "company"
weight = 2

[[main]]
identifier = "contact-us"
name = "Contact us"
url = "contact-us/"
parent = "company"
weight = 3

[[main]]
identifier = "terms"
name = "T&Cs"
url = "terms/"
parent = "company"
weight = 4

[[main]]
identifier = "privacy"
name = "Privacy"
url = "privacy/"
parent = "company"
weight = 5